import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Layout from '../components/home/Layout';
import { Container, Buttons, Button } from '../components/home/Common';
import { withAuth } from '../../utils';

const Home = () => (
  <>
    <Head>
      <title>SURENT</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Layout>
      <Container>
        <h1>
          WELCOME TO <span>SURENT</span>
        </h1>
        <p>ARE YOU A LANDLORD OR TENANT ?</p>

        <Buttons>
          <Link href="/landlord/signin">
            <Button background="#A2293A">LANDLORD</Button>
          </Link>

          <Link href="/tenant/signin">
            <Button background="#242423">TENANT</Button>
          </Link>
        </Buttons>
      </Container>
    </Layout>
  </>
);

export default withAuth(Home);
